import org.cmd.skills.Role
import org.cmd.skills.Skill
import org.cmd.skills.Guild
import org.cmd.skills.User
import org.cmd.skills.UserRole

class BootStrap {

    def init = { servletContext ->
        def adminRole = new Role(authority: 'ROLE_ADMIN').save(flush: true)
        def userRole = new Role(authority: 'ROLE_USER').save(flush: true)

        def testUser = new User(username: 'cdawe', enabled: true, password: 'password')
        testUser.save(flush: true)

        UserRole.create(testUser, adminRole, true)

        createSkills()
        createGuilds()
        bootstrapAssassinPrimaries()
        bootstrapPriestPrimaries()
        bootstrapThiefPrimaries()
        bootstrapWarriorPrimaries()
        //bootstrapMagicPrimaries()
    }
	
    private void createSkills() {
        System.out.println("Bootstrapping Adventuring.")
        new Skill(name: 'adventuring', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.balancing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.tumbling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.vaulting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.direction', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.evaluating', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.evaluating.armour', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.evaluating.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.health', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing.rock', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing.rope', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing.tree', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.following', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.following.evade', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.following.pursuit', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.riding', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.riding.camel', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.riding.horse', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.sailing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.swimming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.perception', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        System.out.println("Bootstrapping Covert.")
        new Skill(name: 'covert', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.casing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.casing.person', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.casing.place', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.hiding', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.hiding.object', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.hiding.person', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.items', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.items.poisons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.items.traps', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.items.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.lockpick', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.lockpick.doors', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.lockpick.safes', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.lockpick.traps', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.manipulation', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.manipulation.palming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.manipulation.passing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.manipulation.sleight-of-hand', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.manipulation.stealing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.stealth', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.stealth.inside', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.stealth.outside', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.stealth.underwater', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        System.out.println("Bootstrapping Crafts.")
        new Skill(name: 'crafts', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.calligraphy', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.design', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.drawing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.painting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.printing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.sculpture', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.coopering', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.furniture', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.turning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.whittling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.baking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.brewing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.butchering', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.cooking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.distilling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.preserving', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.fishing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.foraging', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.tracking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.trapping', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.breeding', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.grooming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.slaughtering', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.edible', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.herbal', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.milling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.tree', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.dyeing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.leatherwork', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.needlework', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.spinning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.tanning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.weaving', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.diagnosis', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.firstaid', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.disease', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.injury', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.poison', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.gem', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.mineral', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.ore', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.ore.panning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.keyboard', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.percussion', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.stringed', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.vocal', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.wind', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.performance', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.special', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.theory', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.firing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.forming', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.forming.shaping', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.forming.throwing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.glazing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.staining', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black.armour', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black.tools', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.cutting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.polishing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.setting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gold', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.locks', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.silver', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        System.out.println("Bootstrapping Faith.")
        new Skill(name: 'faith', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.items', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.items.rod', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.items.scroll', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.curing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.curing.self', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.curing.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.defensive', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.defensive.area', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.defensive.self', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.defensive.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.misc', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.misc.area', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.misc.self', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.misc.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.offensive', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.offensive.area', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.offensive.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.special', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        System.out.println("Bootstrapping Fighting.")
        new Skill(name: 'fighting', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.defence', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.defence.blocking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.defence.dodging', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.defence.parrying', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.axe', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.dagger', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.flail', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.heavy-sword', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.mace', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.misc', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.polearm', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.sword', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.range', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.range.bow', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.range.fired', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.range.thrown', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.mounted', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.tactics', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.unarmed', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.weapon', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.unarmed', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.unarmed.grappling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.unarmed.striking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        System.out.println("Bootstrapping Magic.")
        new Skill(name: 'magic', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.held', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.held.broom', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.held.rod', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.held.staff', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.held.wand', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.scroll', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.talisman', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.worn', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.worn.amulet', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.worn.ring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.elemental', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.elemental.air', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.elemental.earth', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.elemental.fire', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.elemental.water', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.mental', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.mental.animating', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.mental.channeling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.mental.charming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.mental.convoking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.mental.cursing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.binding', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.brewing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.chanting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.dancing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.enchanting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.evoking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.healing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical.scrying', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.spiritual', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.abjuring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.banishing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.conjuring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.divining', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.summoning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.spells', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.spells.defensive', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.spells.misc', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.spells.offensive', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.spells.special', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        System.out.println("Bootstrapping People.")
        new Skill(name: 'people', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.agatean', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.ankh-morporkian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.djelian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.ephebian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.lancrastian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.adventuring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.covert', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.crafts', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.faith', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.fighting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.magic', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.people', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.buying', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.selling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.armour', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.gems', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.jewellery', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
    }
    
    private void createGuilds() {
        log.info("Bootstrapping guilds.")
        
        Guild adventurers = new Guild(name: "Adventurers", root: true).save(flush: true)
        Guild assassins = new Guild(name: "Assassins", root: true).save(flush: true)
        Guild priests = new Guild(name: "Priests", root: true).save(flush: true)
        Guild thieves = new Guild(name: "Thieves", root: true).save(flush: true)
        Guild warriors = new Guild(name: "Warriors", root: true).save(flush: true)
        Guild witches = new Guild(name: "Witches", root: true).save(flush: true)
        Guild wizards = new Guild(name: "Wizards", root: true).save(flush: true)
        
        new Guild(name: "Conlegium Sicariorum", root: false, parent: assassins).save(flush: true)
        new Guild(name: "Hashishim", root: false, parent: assassins).save(flush: true)
        new Guild(name: "Mano Rossa", root: false, parent: assassins).save(flush: true)
        new Guild(name: "Ninja", root: false, parent: assassins).save(flush: true)
        
        new Guild(name: "Fish", root: false, parent: priests).save(flush: true)
        new Guild(name: "Gapp", root: false, parent: priests).save(flush: true)
        new Guild(name: "Gufnork", root: false, parent: priests).save(flush: true)
        new Guild(name: "Hat", root: false, parent: priests).save(flush: true)
        new Guild(name: "Pishe", root: false, parent: priests).save(flush: true)
        new Guild(name: "Sandelfon", root: false, parent: priests).save(flush: true)
        new Guild(name: "Sek", root: false, parent: priests).save(flush: true)
        
        new Guild(name: "Cutpurse", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Mugger", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Prowler", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Safecracker", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Smuggler", root: false, parent: thieves).save(flush: true)
        
        new Guild(name: "Ankh-Morpork Palace Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Djelian Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Hublandish Barbarians", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Hunters", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Imperial Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Klatchian Foreign Legion", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Lancre Highland Regiment", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Musketeers", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Samurai", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Weapon Masters Court", root: false, parent: warriors).save(flush: true)
        
        new Guild(name: "Circle", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Hoodwinkers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Last Order", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Lodgers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Midnight", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Seers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Shadows", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Silver Stars", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Klatch", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Students", root: false, parent: wizards).save(flush: true)
        new Guild(name: "White", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Blue", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Octarine", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Red", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Grey", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Green", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Black", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Brown", root: false, parent: wizards).save(flush: true)
    }
    
    private void bootstrapAssassinPrimaries() {
        System.out.println("Bootstrapping Assassin primaries.")
        
        Skill fidedo = Skill.findByName("fighting.defence.dodging")
        Skill fimeda = Skill.findByName("fighting.melee.dagger")
        Skill fimesw = Skill.findByName("fighting.melee.sword")
        Skill fiunst = Skill.findByName("fighting.unarmed.striking")
        Skill fiungr = Skill.findByName("fighting.unarmed.grappling")
        Skill firath = Skill.findByName("fighting.range.thrown")
        Skill firafi = Skill.findByName("fighting.range.fired")
        
        Skill costin = Skill.findByName("covert.stealth.inside")
        Skill costou = Skill.findByName("covert.stealth.outside")
        Skill cohipe = Skill.findByName("covert.hiding.person")
        Skill cohiob = Skill.findByName("covert.hiding.object")
        Skill colodo = Skill.findByName("covert.lockpick.doors")
        Skill colotr = Skill.findByName("covert.lockpick.traps")
        Skill coitwe = Skill.findByName("covert.items.weapons")
        Skill coittr = Skill.findByName("covert.items.traps")
        Skill coitpo = Skill.findByName("covert.items.poisons")
        Skill comasl = Skill.findByName("covert.manipulation.sleight-of-hand")
        Skill cocape = Skill.findByName("covert.casing.person")
        Skill copo = Skill.findByName("covert.points")
        
        Skill admoclroc = Skill.findByName("adventuring.movement.climbing.rock")
        Skill admoclrop = Skill.findByName("adventuring.movement.climbing.rope")
        Skill admocltr = Skill.findByName("adventuring.movement.climbing.tree")
        Skill admorica = Skill.findByName("adventuring.movement.riding.camel")
        
        Skill pecuag = Skill.findByName("people.culture.agatean")
        
        Guild cs = Guild.findByName("Conlegium Sicariorum")
        cs.addToPrimaries(fidedo)
        cs.addToPrimaries(fimeda)
        cs.addToPrimaries(firath)
        cs.addToPrimaries(firafi)
        cs.addToPrimaries(admoclroc)
        cs.addToPrimaries(admoclrop)
        cs.addToPrimaries(costin)
        cs.addToPrimaries(costou)
        cs.addToPrimaries(cohipe)
        cs.addToPrimaries(colodo)
        cs.addToPrimaries(colotr)
        cs.addToPrimaries(coitpo)
        cs.addToPrimaries(coittr)
        cs.addToPrimaries(coitwe)
        cs.addToPrimaries(copo)
        
        Guild hash = Guild.findByName("Hashishim")
        hash.addToPrimaries(fidedo)
        hash.addToPrimaries(fimeda)
        hash.addToPrimaries(fimesw)
        hash.addToPrimaries(firath)
        hash.addToPrimaries(admorica)
        hash.addToPrimaries(admoclrop)
        hash.addToPrimaries(admoclroc)
        hash.addToPrimaries(costin)
        hash.addToPrimaries(costou)
        hash.addToPrimaries(cohipe)
        hash.addToPrimaries(cohiob)
        hash.addToPrimaries(colodo)
        hash.addToPrimaries(cocape)
        hash.addToPrimaries(coitwe)
        hash.addToPrimaries(copo)
        
        Guild mr = Guild.findByName("Mano Rossa")
        mr.addToPrimaries(fidedo)
        mr.addToPrimaries(fimeda)
        mr.addToPrimaries(fiungr)
        mr.addToPrimaries(firath)
        mr.addToPrimaries(admoclroc)
        mr.addToPrimaries(admocltr)
        mr.addToPrimaries(costin)
        mr.addToPrimaries(costou)
        mr.addToPrimaries(cohipe)
        mr.addToPrimaries(colodo)
        mr.addToPrimaries(colotr)
        mr.addToPrimaries(coittr)
        mr.addToPrimaries(cocape)
        mr.addToPrimaries(coitwe)
        mr.addToPrimaries(copo)
        
        Guild ninja = Guild.findByName("Ninja")
        ninja.addToPrimaries(fidedo)
        ninja.addToPrimaries(fimesw)
        ninja.addToPrimaries(firafi)
        ninja.addToPrimaries(fiunst)
        ninja.addToPrimaries(admoclrop)
        ninja.addToPrimaries(pecuag)
        ninja.addToPrimaries(costin)
        ninja.addToPrimaries(costou)
        ninja.addToPrimaries(cohipe)
        ninja.addToPrimaries(colodo)
        ninja.addToPrimaries(colotr)
        ninja.addToPrimaries(comasl)
        ninja.addToPrimaries(coitpo)
        ninja.addToPrimaries(coitwe)
        ninja.addToPrimaries(copo)
    }
    
    private void bootstrapPriestPrimaries() {
        System.out.println("Bootstrapping Priest primaries.")
        
        Skill faitro = Skill.findByName("faith.items.rod")
        Skill faitsc = Skill.findByName("faith.items.scroll")
        Skill fapo = Skill.findByName("faith.points")
        Skill faricuse = Skill.findByName("faith.rituals.curing.self")
        Skill faricuta = Skill.findByName("faith.rituals.curing.target")
        Skill faridear = Skill.findByName("faith.rituals.defensive.area")
        Skill faridese = Skill.findByName("faith.rituals.defensive.self")
        Skill farideta = Skill.findByName("faith.rituals.defensive.target")
        Skill farimiar = Skill.findByName("faith.rituals.misc.area")
        Skill farimise = Skill.findByName("faith.rituals.misc.self")
        Skill farimita = Skill.findByName("faith.rituals.misc.target")
        Skill fariofar = Skill.findByName("faith.rituals.offensive.area")
        Skill fariofta = Skill.findByName("faith.rituals.offensive.target")
        Skill farisp = Skill.findByName("faith.rituals.special")
        
        Guild fish = Guild.findByName("Fish")
        fish.addToPrimaries(fariofar)
        fish.addToPrimaries(fariofta)
        fish.addToPrimaries(faridear)
        fish.addToPrimaries(faridese)
        fish.addToPrimaries(farideta)
        fish.addToPrimaries(faricuse)
        fish.addToPrimaries(faricuta)
        fish.addToPrimaries(farimiar)
        fish.addToPrimaries(farimise)
        fish.addToPrimaries(farimita)
        fish.addToPrimaries(farisp)
        fish.addToPrimaries(faitro)
        fish.addToPrimaries(faitsc)
        fish.addToPrimaries(fapo)
        
        Guild gapp = Guild.findByName("Gapp")
        gapp.addToPrimaries(fariofar)
        gapp.addToPrimaries(fariofta)
        gapp.addToPrimaries(faridear)
        gapp.addToPrimaries(faridese)
        gapp.addToPrimaries(farideta)
        gapp.addToPrimaries(faricuse)
        gapp.addToPrimaries(faricuta)
        gapp.addToPrimaries(farimiar)
        gapp.addToPrimaries(farimise)
        gapp.addToPrimaries(farimita)
        gapp.addToPrimaries(farisp)
        gapp.addToPrimaries(faitro)
        gapp.addToPrimaries(faitsc)
        gapp.addToPrimaries(fapo)
        
        Guild gufnork = Guild.findByName("Gufnork")
        gufnork.addToPrimaries(fariofar)
        gufnork.addToPrimaries(fariofta)
        gufnork.addToPrimaries(faridear)
        gufnork.addToPrimaries(faridese)
        gufnork.addToPrimaries(farideta)
        gufnork.addToPrimaries(faricuse)
        gufnork.addToPrimaries(faricuta)
        gufnork.addToPrimaries(farimiar)
        gufnork.addToPrimaries(farimise)
        gufnork.addToPrimaries(farimita)
        gufnork.addToPrimaries(farisp)
        gufnork.addToPrimaries(faitro)
        gufnork.addToPrimaries(faitsc)
        gufnork.addToPrimaries(fapo)
        
        Guild hat = Guild.findByName("Hat")
        hat.addToPrimaries(fariofar)
        hat.addToPrimaries(fariofta)
        hat.addToPrimaries(faridear)
        hat.addToPrimaries(faridese)
        hat.addToPrimaries(farideta)
        hat.addToPrimaries(faricuse)
        hat.addToPrimaries(faricuta)
        hat.addToPrimaries(farimiar)
        hat.addToPrimaries(farimise)
        hat.addToPrimaries(farimita)
        hat.addToPrimaries(farisp)
        hat.addToPrimaries(faitro)
        hat.addToPrimaries(faitsc)
        hat.addToPrimaries(fapo)
        
        Guild pishe = Guild.findByName("Pishe")
        pishe.addToPrimaries(fariofar)
        pishe.addToPrimaries(fariofta)
        pishe.addToPrimaries(faridear)
        pishe.addToPrimaries(faridese)
        pishe.addToPrimaries(farideta)
        pishe.addToPrimaries(faricuse)
        pishe.addToPrimaries(faricuta)
        pishe.addToPrimaries(farimiar)
        pishe.addToPrimaries(farimise)
        pishe.addToPrimaries(farimita)
        pishe.addToPrimaries(farisp)
        pishe.addToPrimaries(faitro)
        pishe.addToPrimaries(faitsc)
        pishe.addToPrimaries(fapo)
        
        Guild sandelfon = Guild.findByName("Sandelfon")
        sandelfon.addToPrimaries(fariofar)
        sandelfon.addToPrimaries(fariofta)
        sandelfon.addToPrimaries(faridear)
        sandelfon.addToPrimaries(faridese)
        sandelfon.addToPrimaries(farideta)
        sandelfon.addToPrimaries(faricuse)
        sandelfon.addToPrimaries(faricuta)
        sandelfon.addToPrimaries(farimiar)
        sandelfon.addToPrimaries(farimise)
        sandelfon.addToPrimaries(farimita)
        sandelfon.addToPrimaries(farisp)
        sandelfon.addToPrimaries(faitro)
        sandelfon.addToPrimaries(faitsc)
        sandelfon.addToPrimaries(fapo)
        
        Guild sek = Guild.findByName("Sek")
        sek.addToPrimaries(fariofar)
        sek.addToPrimaries(fariofta)
        sek.addToPrimaries(faridear)
        sek.addToPrimaries(faridese)
        sek.addToPrimaries(farideta)
        sek.addToPrimaries(faricuse)
        sek.addToPrimaries(faricuta)
        sek.addToPrimaries(farimiar)
        sek.addToPrimaries(farimise)
        sek.addToPrimaries(farimita)
        sek.addToPrimaries(farisp)
        sek.addToPrimaries(faitro)
        sek.addToPrimaries(faitsc)
        sek.addToPrimaries(fapo)
    }
    
   private void bootstrapThiefPrimaries() {
        System.out.println("Bootstrapping Thief primaries.")
        
        Skill fidedo = Skill.findByName("fighting.defence.dodging")
        Skill fimeda = Skill.findByName("fighting.melee.dagger")
        Skill fimesw = Skill.findByName("fighting.melee.sword")
        Skill fimema = Skill.findByName("fighting.melee.mace")
        Skill fiunst = Skill.findByName("fighting.unarmed.striking")
        Skill firath = Skill.findByName("fighting.range.thrown")
        
        Skill costin = Skill.findByName("covert.stealth.inside")
        Skill costou = Skill.findByName("covert.stealth.outside")
        Skill cohipe = Skill.findByName("covert.hiding.person")
        Skill cohiob = Skill.findByName("covert.hiding.object")
        Skill colodo = Skill.findByName("covert.lockpick.doors")
        Skill colotr = Skill.findByName("covert.lockpick.traps")
        Skill colosa = Skill.findByName("covert.lockpick.safes")
        Skill coitwe = Skill.findByName("covert.items.weapons")
        Skill coittr = Skill.findByName("covert.items.traps")
        Skill coitpo = Skill.findByName("covert.items.poisons")
        Skill comasl = Skill.findByName("covert.manipulation.sleight-of-hand")
        Skill comast = Skill.findByName("covert.manipulation.stealing")
        Skill comapas = Skill.findByName("covert.manipulation.passing")
        Skill comapal = Skill.findByName("covert.manipulation.palming")
        Skill cocape = Skill.findByName("covert.casing.person")
        Skill cocapl = Skill.findByName("covert.casing.place")
        Skill cocaob = Skill.findByName("covert.casing.object")
        Skill copo = Skill.findByName("covert.points")
        
        Skill adevwe = Skill.findByName("adventuring.evaluating.weapons")
        Skill adevar = Skill.findByName("adventuring.evaluating.armour")
        
        Skill petrvage = Skill.findByName("people.trading.valueing.gems")
        Skill petrvaje = Skill.findByName("people.trading.valueing.jewellery")
        Skill petrvaar = Skill.findByName("people.trading.valueing.armour")
        Skill petrvawe = Skill.findByName("people.trading.valueing.weapons")
        
        Guild cutpurse = Guild.findByName("Cutpurse")
        cutpurse.addToPrimaries(costin)
        cutpurse.addToPrimaries(costou)
        cutpurse.addToPrimaries(cohipe)
        cutpurse.addToPrimaries(cohiob)
        cutpurse.addToPrimaries(colodo)
        cutpurse.addToPrimaries(comapas)
        cutpurse.addToPrimaries(comast)
        cutpurse.addToPrimaries(comapal)
        cutpurse.addToPrimaries(comasl)
        cutpurse.addToPrimaries(cocape)
        cutpurse.addToPrimaries(copo)
        cutpurse.addToPrimaries(fimeda)
        cutpurse.addToPrimaries(firath)
        cutpurse.addToPrimaries(petrvage)
        cutpurse.addToPrimaries(petrvaje)
        
        Guild mugger = Guild.findByName("Mugger")
        mugger.addToPrimaries(costin)
        mugger.addToPrimaries(costou)
        mugger.addToPrimaries(cohipe)
        mugger.addToPrimaries(cohiob)
        mugger.addToPrimaries(colodo)
        mugger.addToPrimaries(comapal)
        mugger.addToPrimaries(comast)
        mugger.addToPrimaries(cocape)
        mugger.addToPrimaries(cocapl)
        mugger.addToPrimaries(copo)
        mugger.addToPrimaries(fimesw)
        mugger.addToPrimaries(fimema)
        mugger.addToPrimaries(firath)
        mugger.addToPrimaries(petrvage)
        mugger.addToPrimaries(petrvaje)
        
        Guild prowler = Guild.findByName("Prowler")
        prowler.addToPrimaries(costin)
        prowler.addToPrimaries(costou)
        prowler.addToPrimaries(cohipe)
        prowler.addToPrimaries(cohiob)
        prowler.addToPrimaries(colodo)
        prowler.addToPrimaries(colotr)
        prowler.addToPrimaries(comast)
        prowler.addToPrimaries(comapas)
        prowler.addToPrimaries(comapal)
        prowler.addToPrimaries(cocape)
        prowler.addToPrimaries(cocapl)
        prowler.addToPrimaries(copo)
        prowler.addToPrimaries(firath)
        prowler.addToPrimaries(petrvage)
        prowler.addToPrimaries(petrvaje)
        
        Guild safecracker = Guild.findByName("Safecracker")
        safecracker.addToPrimaries(costin)
        safecracker.addToPrimaries(costou)
        safecracker.addToPrimaries(cohipe)
        safecracker.addToPrimaries(cohiob)
        safecracker.addToPrimaries(colodo)
        safecracker.addToPrimaries(colosa)
        safecracker.addToPrimaries(colotr)
        safecracker.addToPrimaries(coittr)
        safecracker.addToPrimaries(comapas)
        safecracker.addToPrimaries(comasl)
        safecracker.addToPrimaries(cocapl)
        safecracker.addToPrimaries(copo)
        safecracker.addToPrimaries(firath)
        safecracker.addToPrimaries(petrvage)
        safecracker.addToPrimaries(petrvaje)
        
        Guild smuggler = Guild.findByName("Smuggler")
        smuggler.addToPrimaries(costin)
        smuggler.addToPrimaries(costou)
        smuggler.addToPrimaries(cohipe)
        smuggler.addToPrimaries(cohiob)
        smuggler.addToPrimaries(comapal)
        smuggler.addToPrimaries(comapas)
        smuggler.addToPrimaries(copo)
        smuggler.addToPrimaries(fimesw)
        smuggler.addToPrimaries(firath)
        smuggler.addToPrimaries(petrvage)
        smuggler.addToPrimaries(petrvaje)
        smuggler.addToPrimaries(petrvawe)
        smuggler.addToPrimaries(petrvaar)
        smuggler.addToPrimaries(adevar)
        smuggler.addToPrimaries(adevwe)
    }
    
    private void bootstrapWarriorPrimaries() {
        System.out.println("Bootstrapping Warrior primaries.")
        
        Skill fidedo = Skill.findByName("fighting.defence.dodging")
        Skill fidepa = Skill.findByName("fighting.defence.parrying")
        Skill fidebl = Skill.findByName("fighting.defence.blocking")
        Skill fimeda = Skill.findByName("fighting.melee.dagger")
        Skill fimema = Skill.findByName("fighting.melee.mace")
        Skill fimefl = Skill.findByName("fighting.melee.flail")
        Skill fimepo = Skill.findByName("fighting.melee.polearm")
        Skill fimeax = Skill.findByName("fighting.melee.axe")
        Skill fimesw = Skill.findByName("fighting.melee.sword")
        Skill fimehe = Skill.findByName("fighting.melee.heavy-sword")
        Skill fiunst = Skill.findByName("fighting.unarmed.striking")
        Skill fiungr = Skill.findByName("fighting.unarmed.grappling")
        Skill firath = Skill.findByName("fighting.range.thrown")
        Skill firafi = Skill.findByName("fighting.range.fired")
        Skill firabo = Skill.findByName("fighting.range.bow")
        Skill fispwe = Skill.findByName("fighting.special.weapon")
        Skill fispta = Skill.findByName("fighting.special.tactics")
        Skill fipo = Skill.findByName("fighting.points")
        
        Skill crsmblwe = Skill.findByName("crafts.smithing.black.weapons")
        Skill crmefi = Skill.findByName("crafts.medicine.firstaid")
        Skill crhutrac = Skill.findByName("crafts.hunting.tracking")
        Skill crhutrap = Skill.findByName("crafts.hunting.trapping")
        Skill cratca = Skill.findByName("crafts.arts.calligraphy")
        Skill crmale = Skill.findByName("crafts.materials.leatherwork")
        Skill crmuinst = Skill.findByName("crafts.music.instruments.stringed")
        Skill crmuinvo = Skill.findByName("crafts.music.instruments.vocal")
        
        Skill adevar = Skill.findByName("adventuring.evaluating.armour")
        Skill adevwe = Skill.findByName("adventuring.evaluating.weapons")
        Skill addi = Skill.findByName("adventuring.direction")
        Skill admoclroc = Skill.findByName("adventuring.movement.climbing.rock")
        Skill admocltr = Skill.findByName("adventuring.movement.climbing.tree")
        Skill admoriho = Skill.findByName("adventuring.movement.riding.horse")
        Skill admorica = Skill.findByName("adventuring.movement.riding.camel")
    
        Guild ampg = Guild.findByName("Ankh-Morpork Palace Guard")
        ampg.addToPrimaries(crsmblwe)
        ampg.addToPrimaries(fidebl)
        ampg.addToPrimaries(fidepa)
        ampg.addToPrimaries(fimefl)
        ampg.addToPrimaries(fimehe)
        ampg.addToPrimaries(fimema)
        ampg.addToPrimaries(fimesw)
        ampg.addToPrimaries(fipo)
        ampg.addToPrimaries(firath)
        ampg.addToPrimaries(fispta)
        ampg.addToPrimaries(fispwe)
        ampg.addToPrimaries(fiunst)
        ampg.addToPrimaries(adevar)
        ampg.addToPrimaries(adevwe)
        ampg.addToPrimaries(crmefi)
        
        Guild djelian = Guild.findByName("Djelian Guard")
        djelian.addToPrimaries(crsmblwe)
        djelian.addToPrimaries(fidebl)
        djelian.addToPrimaries(fidepa)
        djelian.addToPrimaries(fimeda)
        djelian.addToPrimaries(fimema)
        djelian.addToPrimaries(fimepo)
        djelian.addToPrimaries(fimesw)
        djelian.addToPrimaries(fipo)
        djelian.addToPrimaries(firabo)
        djelian.addToPrimaries(fispta)
        djelian.addToPrimaries(fispwe)
        djelian.addToPrimaries(fiungr)
        djelian.addToPrimaries(adevar)
        djelian.addToPrimaries(adevwe)
        djelian.addToPrimaries(addi)
        
        Guild barb = Guild.findByName("Hublandish Barbarians")
        barb.addToPrimaries(crmale)
        barb.addToPrimaries(crmefi)
        barb.addToPrimaries(fidedo)
        barb.addToPrimaries(fidepa)
        barb.addToPrimaries(fidedo)
        barb.addToPrimaries(fimeax)
        barb.addToPrimaries(fimehe)
        barb.addToPrimaries(fimema)
        barb.addToPrimaries(fimefl)
        barb.addToPrimaries(fipo)
        barb.addToPrimaries(firath)
        barb.addToPrimaries(fispwe)
        barb.addToPrimaries(fiungr)
        barb.addToPrimaries(fiunst)
        barb.addToPrimaries(admoriho)
        
        Guild hunters = Guild.findByName("Hunters")
        hunters.addToPrimaries(crhutrac)
        hunters.addToPrimaries(crhutrap)
        hunters.addToPrimaries(crmale)
        hunters.addToPrimaries(crmefi)
        hunters.addToPrimaries(fidedo)
        hunters.addToPrimaries(fidepa)
        hunters.addToPrimaries(fimeax)
        hunters.addToPrimaries(fimeda)
        hunters.addToPrimaries(fimema)
        hunters.addToPrimaries(fimesw)
        hunters.addToPrimaries(fipo)
        hunters.addToPrimaries(firabo)
        hunters.addToPrimaries(fispta)
        hunters.addToPrimaries(fispwe)
        hunters.addToPrimaries(admocltr)
        
        Guild imps = Guild.findByName("Imperial Guard")
        imps.addToPrimaries(crsmblwe)
        imps.addToPrimaries(fidebl)
        imps.addToPrimaries(fidepa)
        imps.addToPrimaries(fimefl)
        imps.addToPrimaries(fimema)
        imps.addToPrimaries(fimepo)
        imps.addToPrimaries(fimesw)
        imps.addToPrimaries(fipo)
        imps.addToPrimaries(firafi)
        imps.addToPrimaries(fispta)
        imps.addToPrimaries(fispwe)
        imps.addToPrimaries(fiungr)
        imps.addToPrimaries(adevwe)
        imps.addToPrimaries(admoclroc)
        imps.addToPrimaries(adevar)
        
        Guild kfl = Guild.findByName("Klatchian Foreign Legion")
        kfl.addToPrimaries(crmefi)
        kfl.addToPrimaries(fidebl)
        kfl.addToPrimaries(fidepa)
        kfl.addToPrimaries(fimeda)
        kfl.addToPrimaries(fimema)
        kfl.addToPrimaries(fimepo)
        kfl.addToPrimaries(fimesw)
        kfl.addToPrimaries(fipo)
        kfl.addToPrimaries(firabo)
        kfl.addToPrimaries(fispta)
        kfl.addToPrimaries(fispwe)
        kfl.addToPrimaries(fiunst)
        kfl.addToPrimaries(addi)
        kfl.addToPrimaries(admorica)
        kfl.addToPrimaries(adevwe)
        
        Guild lancre = Guild.findByName("Lancre Highland Regiment")
        lancre.addToPrimaries(crmefi)
        lancre.addToPrimaries(crsmblwe)
        lancre.addToPrimaries(fidebl)
        lancre.addToPrimaries(fidepa)
        lancre.addToPrimaries(fimeax)
        lancre.addToPrimaries(fimema)
        lancre.addToPrimaries(fimepo)
        lancre.addToPrimaries(fimesw)
        lancre.addToPrimaries(fipo)
        lancre.addToPrimaries(firabo)
        lancre.addToPrimaries(fispta)
        lancre.addToPrimaries(fispwe)
        lancre.addToPrimaries(fiunst)
        lancre.addToPrimaries(admoriho)
        lancre.addToPrimaries(crhutrac)
        
        //Guild musket = Guild.findByName("Musketeers")
        //Guild samurai = Guild.findByName("Samurai")
        //Guild masters = Guild.findByName("Weapon Masters Court")
    }
    
/*    private void bootstrapMagicPrimaries() {
        Guild witches = new Guild(name: "Witches", root: true).save(flush: true)
        witches.addToPrimaries(maspof)
        witches.addToPrimaries(maspde)
        witches.addToPrimaries(maspmi)
        witches.addToPrimaries(maspsp)
        witches.addToPrimaries(mamemechan)
        witches.addToPrimaries(mamemechar)
        witches.addToPrimaries(mamemecu)
        witches.addToPrimaries(mamephbr)
        witches.addToPrimaries(mamephch)
        witches.addToPrimaries(mamephda)
        witches.addToPrimaries(maithebr)
        witches.addToPrimaries(maitwoam)
        witches.addToPrimaries(maitwori)
        witches.addToPrimaries(maitta)
        witches.addToPrimaries(mapo)
    } */
	
    def destroy = {
        
    }
}