import org.cmd.skills.Role
import org.cmd.skills.Skill
import org.cmd.skills.Guild
import org.cmd.skills.User
import org.cmd.skills.UserRole

class BootStrap {

    def init = { servletContext ->
        def adminRole = new Role(authority: 'ROLE_ADMIN').save(flush: true)
        def userRole = new Role(authority: 'ROLE_USER').save(flush: true)

        def testUser = new User(username: 'cdawe', enabled: true, password: 'password')
        testUser.save(flush: true)

        UserRole.create(testUser, adminRole, true)

        createSkills()
        createGuilds()
    }
	
    private void createSkills() {
        log.info("Bootstrapping skills.")

        new Skill(name: 'adventuring', root: true, leaf: false).save(flush: true)
        new Skill(name: 'adventuring.acrobatics', root: false, leaf: false).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.balancing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.tumbling', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.vaulting', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.direction', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.evaluating', root: false, leaf: false).save(flush: true)
        new Skill(name: 'adventuring.evaluating.armour', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.evaluating.weapons', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.health', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement', root: false, leaf: false).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing', root: false, leaf: false).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing.rock', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing.rope', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing.tree', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.following', root: false, leaf: false).save(flush: true)
        new Skill(name: 'adventuring.movement.following.evade', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.following.pursuit', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.riding', root: false, leaf: false).save(flush: true)
        new Skill(name: 'adventuring.movement.riding.camel', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.riding.horse', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.sailing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.movement.swimming', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.perception', root: false, leaf: true).save(flush: true)
        new Skill(name: 'adventuring.points', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert', root: true, leaf: false).save(flush: true)
        new Skill(name: 'covert.casing', root: false, leaf: false).save(flush: true)
        new Skill(name: 'covert.casing.person', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.casing.place', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.hiding', root: false, leaf: false).save(flush: true)
        new Skill(name: 'covert.hiding.object', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.hiding.person', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.items', root: false, leaf: false).save(flush: true)
        new Skill(name: 'covert.items.poisons', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.items.traps', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.items.weapons', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.lockpick', root: false, leaf: false).save(flush: true)
        new Skill(name: 'covert.lockpick.doors', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.lockpick.safes', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.lockpick.traps', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.manipulation', root: false, leaf: false).save(flush: true)
        new Skill(name: 'covert.manipulation.palming', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.manipulation.passing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.manipulation.sleight-of-hand', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.manipulation.stealing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.points', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.stealth', root: false, leaf: false).save(flush: true)
        new Skill(name: 'covert.stealth.inside', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.stealth.outside', root: false, leaf: true).save(flush: true)
        new Skill(name: 'covert.stealth.underwater', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts', root: true, leaf: false).save(flush: true)
        new Skill(name: 'crafts.arts', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.arts.calligraphy', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.arts.design', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.arts.drawing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.arts.painting', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.arts.printing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.arts.sculpture', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.carpentry', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.carpentry.coopering', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.carpentry.furniture', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.carpentry.turning', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.carpentry.whittling', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.culinary', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.culinary.baking', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.culinary.brewing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.culinary.butchering', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.culinary.cooking', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.culinary.distilling', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.culinary.preserving', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.hunting', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.hunting.fishing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.hunting.foraging', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.hunting.tracking', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.hunting.trapping', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.husbandry', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.breeding', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.grooming', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.slaughtering', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.edible', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.herbal', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.milling', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.tree', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.materials', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.materials.dyeing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.materials.leatherwork', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.materials.needlework', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.materials.spinning', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.materials.tanning', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.materials.weaving', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.medicine', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.medicine.diagnosis', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.medicine.firstaid', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.disease', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.injury', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.poison', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.mining', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.mining.gem', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.mining.mineral', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.mining.ore', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.mining.ore.panning', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.music.instruments', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.music.instruments.keyboard', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music.instruments.percussion', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music.instruments.stringed', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music.instruments.vocal', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music.instruments.wind', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music.performance', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music.special', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.music.theory', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.points', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.pottery', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.pottery.firing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.pottery.forming', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.pottery.forming.shaping', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.pottery.forming.throwing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.pottery.glazing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.pottery.staining', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.smithing.black', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.smithing.black.armour', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.black.tools', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.black.weapons', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.gem', root: false, leaf: false).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.cutting', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.polishing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.setting', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.gold', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.locks', root: false, leaf: true).save(flush: true)
        new Skill(name: 'crafts.smithing.silver', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith', root: true, leaf: false).save(flush: true)
        new Skill(name: 'faith.items', root: false, leaf: false).save(flush: true)
        new Skill(name: 'faith.items.rod', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.items.scroll', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.points', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals', root: false, leaf: false).save(flush: true)
        new Skill(name: 'faith.rituals.curing', root: false, leaf: false).save(flush: true)
        new Skill(name: 'faith.rituals.curing.self', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.curing.target', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.defensive', root: false, leaf: false).save(flush: true)
        new Skill(name: 'faith.rituals.defensive.area', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.defensive.self', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.defensive.target', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.misc', root: false, leaf: false).save(flush: true)
        new Skill(name: 'faith.rituals.misc.area', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.misc.self', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.misc.target', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.offensive', root: false, leaf: false).save(flush: true)
        new Skill(name: 'faith.rituals.offensive.area', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.offensive.target', root: false, leaf: true).save(flush: true)
        new Skill(name: 'faith.rituals.special', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting', root: true, leaf: false).save(flush: true)
        new Skill(name: 'fighting.defence', root: false, leaf: false).save(flush: true)
        new Skill(name: 'fighting.defence.blocking', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.defence.dodging', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.defence.parrying', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee', root: false, leaf: false).save(flush: true)
        new Skill(name: 'fighting.melee.axe', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee.dagger', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee.flail', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee.heavy-sword', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee.mace', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee.misc', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee.polearm', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.melee.sword', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.points', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.range', root: false, leaf: false).save(flush: true)
        new Skill(name: 'fighting.range.bow', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.range.fired', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.range.thrown', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.special', root: false, leaf: false).save(flush: true)
        new Skill(name: 'fighting.special.mounted', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.special.tactics', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.special.unarmed', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.special.weapon', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.unarmed', root: false, leaf: false).save(flush: true)
        new Skill(name: 'fighting.unarmed.grappling', root: false, leaf: true).save(flush: true)
        new Skill(name: 'fighting.unarmed.striking', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic', root: true, leaf: false).save(flush: true)
        new Skill(name: 'magic.items', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.items.held', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.items.held.broom', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.items.held.rod', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.items.held.staff', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.items.held.wand', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.items.scroll', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.items.talisman', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.items.worn', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.items.worn.amulet', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.items.worn.ring', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.methods.elemental', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.methods.elemental.air', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.elemental.earth', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.elemental.fire', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.elemental.water', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.mental', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.methods.mental.animating', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.mental.channeling', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.mental.charming', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.mental.convoking', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.mental.cursing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.methods.physical.binding', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical.brewing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical.chanting', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical.dancing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical.enchanting', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical.evoking', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical.healing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.physical.scrying', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.spiritual', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.abjuring', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.banishing', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.conjuring', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.divining', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.methods.spiritual.summoning', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.points', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.spells', root: false, leaf: false).save(flush: true)
        new Skill(name: 'magic.spells.defensive', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.spells.misc', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.spells.offensive', root: false, leaf: true).save(flush: true)
        new Skill(name: 'magic.spells.special', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people', root: true, leaf: false).save(flush: true)
        new Skill(name: 'people.culture', root: false, leaf: false).save(flush: true)
        new Skill(name: 'people.culture.agatean', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.culture.ankh-morporkian', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.culture.djelian', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.culture.ephebian', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.culture.lancrastian', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.points', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.teaching', root: false, leaf: false).save(flush: true)
        new Skill(name: 'people.teaching.adventuring', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.teaching.covert', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.teaching.crafts', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.teaching.faith', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.teaching.fighting', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.teaching.magic', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.teaching.people', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.trading', root: false, leaf: false).save(flush: true)
        new Skill(name: 'people.trading.buying', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.trading.selling', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.trading.valueing', root: false, leaf: false).save(flush: true)
        new Skill(name: 'people.trading.valueing.armour', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.trading.valueing.gems', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.trading.valueing.jewellery', root: false, leaf: true).save(flush: true)
        new Skill(name: 'people.trading.valueing.weapons', root: false, leaf: true).save(flush: true)
    }
    
    private void createGuilds() {
        log.info("Bootstrapping guilds.")
        
        Guild adventurers = new Guild(longName: "Adventurers", shortName: "Adventurers", root: true).save(flush: true)
        Guild assassins = new Guild(longName: "Assassins", shortName: "Assassins", root: true).save(flush: true)
        Guild priests = new Guild(longName: "Priests", shortName: "Priests", root: true).save(flush: true)
        Guild thieves = new Guild(longName: "Thieves", shortName: "Thieves", root: true).save(flush: true)
        Guild warriors = new Guild(longName: "Warriors", shortName: "Warriors", root: true).save(flush: true)
        Guild witches = new Guild(longName: "Witches", shortName: "Witches", root: true).save(flush: true)
        Guild wizards = new Guild(longName: "Wizards", shortName: "Wizards", root: true).save(flush: true)
        
        new Guild(longName: "Conlegium Sicariorum", shortName: "CS", root: false).save(flush: true)
        new Guild(longName: "Hashishim", shortName: "Hashishim", root: false).save(flush: true)
        new Guild(longName: "Mano Rossa", shortName: "Mano Rossa", root: false).save(flush: true)
        new Guild(longName: "Ninja", shortName: "Ninja", root: false).save(flush: true)
        
        new Guild(longName: "Fish", shortName: "Fish", root: false).save(flush: true)
        new Guild(longName: "Gapp", shortName: "Gapp", root: false).save(flush: true)
        new Guild(longName: "Gufnork", shortName: "Gufnork", root: false).save(flush: true)
        new Guild(longName: "Hat", shortName: "Hat", root: false).save(flush: true)
        new Guild(longName: "Pishe", shortName: "Pishe", root: false).save(flush: true)
        new Guild(longName: "Sandelfon", shortName: "Sandelfon", root: false).save(flush: true)
        new Guild(longName: "Sek", shortName: "Sek", root: false).save(flush: true)
    }
	
    def destroy = {
        
    }
}
