import org.cmd.skills.Role
import org.cmd.skills.Skill
import org.cmd.skills.Guild
import org.cmd.skills.User
import org.cmd.skills.UserRole

class BootStrap {

    def init = { servletContext ->
        def adminRole = new Role(authority: 'ROLE_ADMIN').save(flush: true)
        def userRole = new Role(authority: 'ROLE_USER').save(flush: true)

        def testUser = new User(username: 'cdawe', enabled: true, password: 'password')
        testUser.save(flush: true)

        UserRole.create(testUser, adminRole, true)

        createSkills()
//        createGuilds()
    }
	
    private void createSkills() {
        log.info("Bootstrapping skills.")

        new Skill(name: 'adventuring', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.balancing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.tumbling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.acrobatics.vaulting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.direction', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.evaluating', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.evaluating.armour', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.evaluating.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.health', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.climbing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill admoclroc = new Skill(name: 'adventuring.movement.climbing.rock', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill admoclrop = new Skill(name: 'adventuring.movement.climbing.rope', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill admocltr = new Skill(name: 'adventuring.movement.climbing.tree', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.following', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.following.evade', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.following.pursuit', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.riding', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill admorica = new Skill(name: 'adventuring.movement.riding.camel', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.riding.horse', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.sailing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.movement.swimming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.perception', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'adventuring.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        new Skill(name: 'covert', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.casing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill cocape = new Skill(name: 'covert.casing.person', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill cocapl = new Skill(name: 'covert.casing.place', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.hiding', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill cohiob = new Skill(name: 'covert.hiding.object', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill cohipe = new Skill(name: 'covert.hiding.person', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.items', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill coitpo = new Skill(name: 'covert.items.poisons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill coittr = new Skill(name: 'covert.items.traps', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill coitwe = new Skill(name: 'covert.items.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.lockpick', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill colodo = new Skill(name: 'covert.lockpick.doors', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill colosa = new Skill(name: 'covert.lockpick.safes', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill colotr = new Skill(name: 'covert.lockpick.traps', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.manipulation', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill comapal = new Skill(name: 'covert.manipulation.palming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill comapas = new Skill(name: 'covert.manipulation.passing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill comasl = new Skill(name: 'covert.manipulation.sleight-of-hand', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill comast = new Skill(name: 'covert.manipulation.stealing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill copo = new Skill(name: 'covert.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.stealth', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill costin = new Skill(name: 'covert.stealth.inside', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill costou = new Skill(name: 'covert.stealth.outside', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'covert.stealth.underwater', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        new Skill(name: 'crafts', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.calligraphy', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.design', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.drawing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.painting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.printing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.arts.sculpture', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.coopering', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.furniture', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.turning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.carpentry.whittling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.baking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.brewing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.butchering', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.cooking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.distilling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.culinary.preserving', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.fishing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.foraging', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.tracking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.hunting.trapping', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.breeding', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.grooming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.animal.slaughtering', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.edible', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.herbal', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.milling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.husbandry.plant.tree', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.dyeing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.leatherwork', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.needlework', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.spinning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.tanning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.materials.weaving', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.diagnosis', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.firstaid', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.disease', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.injury', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.medicine.treatment.poison', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.gem', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.mineral', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.ore', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.mining.ore.panning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.keyboard', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.percussion', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.stringed', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.vocal', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.instruments.wind', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.performance', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.special', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.music.theory', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.firing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.forming', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.forming.shaping', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.forming.throwing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.glazing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.pottery.staining', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black.armour', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black.tools', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.black.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.cutting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.polishing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gem.setting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.gold', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.locks', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'crafts.smithing.silver', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        new Skill(name: 'faith', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.items', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill faitro = new Skill(name: 'faith.items.rod', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill faitsc = new Skill(name: 'faith.items.scroll', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fapo = new Skill(name: 'faith.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.curing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill faricuse = new Skill(name: 'faith.rituals.curing.self', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill faricuta = new Skill(name: 'faith.rituals.curing.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.defensive', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill faridear = new Skill(name: 'faith.rituals.defensive.area', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill faridese = new Skill(name: 'faith.rituals.defensive.self', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill farideta = new Skill(name: 'faith.rituals.defensive.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.misc', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill farimiar = new Skill(name: 'faith.rituals.misc.area', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill farimise = new Skill(name: 'faith.rituals.misc.self', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill farimita = new Skill(name: 'faith.rituals.misc.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'faith.rituals.offensive', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fariofar = new Skill(name: 'faith.rituals.offensive.area', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fariofta = new Skill(name: 'faith.rituals.offensive.target', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill farisp = new Skill(name: 'faith.rituals.special', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        new Skill(name: 'fighting', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.defence', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.defence.blocking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fidedo = new Skill(name: 'fighting.defence.dodging', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.defence.parrying', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.axe', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fimeda = new Skill(name: 'fighting.melee.dagger', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.flail', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.heavy-sword', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.mace', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.misc', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.melee.polearm', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fimesw = new Skill(name: 'fighting.melee.sword', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.range', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.range.bow', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill firafi = new Skill(name: 'fighting.range.fired', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill firath = new Skill(name: 'fighting.range.thrown', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.mounted', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.tactics', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.unarmed', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.special.weapon', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'fighting.unarmed', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fiungr = new Skill(name: 'fighting.unarmed.grappling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill fiunst = new Skill(name: 'fighting.unarmed.striking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        new Skill(name: 'magic', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.held', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maithebr = new Skill(name: 'magic.items.held.broom', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maithero = new Skill(name: 'magic.items.held.rod', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maithest = new Skill(name: 'magic.items.held.staff', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maithewa = new Skill(name: 'magic.items.held.wand', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maitsc = new Skill(name: 'magic.items.scroll', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maitta = new Skill(name: 'magic.items.talisman', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.items.worn', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maitwoam = new Skill(name: 'magic.items.worn.amulet', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maitwori = new Skill(name: 'magic.items.worn.ring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.elemental', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mameelai = new Skill(name: 'magic.methods.elemental.air', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mameelea = new Skill(name: 'magic.methods.elemental.earth', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mameelfi = new Skill(name: 'magic.methods.elemental.fire', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mameelwa = new Skill(name: 'magic.methods.elemental.water', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.mental', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamemean = new Skill(name: 'magic.methods.mental.animating', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamemechan = new Skill(name: 'magic.methods.mental.channeling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamemechar = new Skill(name: 'magic.methods.mental.charming', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamemeco = new Skill(name: 'magic.methods.mental.convoking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamemecu = new Skill(name: 'magic.methods.mental.cursing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.physical', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephbi = new Skill(name: 'magic.methods.physical.binding', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephbr = new Skill(name: 'magic.methods.physical.brewing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephch = new Skill(name: 'magic.methods.physical.chanting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephda = new Skill(name: 'magic.methods.physical.dancing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephen = new Skill(name: 'magic.methods.physical.enchanting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephev = new Skill(name: 'magic.methods.physical.evoking', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephhe = new Skill(name: 'magic.methods.physical.healing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamephsc = new Skill(name: 'magic.methods.physical.scrying', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.methods.spiritual', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamespab = new Skill(name: 'magic.methods.spiritual.abjuring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamespba = new Skill(name: 'magic.methods.spiritual.banishing', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamespco = new Skill(name: 'magic.methods.spiritual.conjuring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamespdi = new Skill(name: 'magic.methods.spiritual.divining', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mamespsu = new Skill(name: 'magic.methods.spiritual.summoning', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill mapo = new Skill(name: 'magic.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'magic.spells', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maspde = new Skill(name: 'magic.spells.defensive', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maspmi = new Skill(name: 'magic.spells.misc', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maspof = new Skill(name: 'magic.spells.offensive', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill maspsp = new Skill(name: 'magic.spells.special', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        new Skill(name: 'people', root: true, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        Skill pecuag = new Skill(name: 'people.culture.agatean', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.ankh-morporkian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.djelian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.ephebian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.culture.lancrastian', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.points', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.adventuring', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.covert', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.crafts', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.faith', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.fighting', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.magic', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.teaching.people', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.buying', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.selling', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing', root: false, leaf: false, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.armour', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.gems', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.jewellery', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        new Skill(name: 'people.trading.valueing.weapons', root: false, leaf: true, constitution: 1, dexterity: 1, intelligence: 1, strength: 1, wisdom: 1).save(flush: true)
        
        log.info("Bootstrapping guilds.")
        
        Guild adventurers = new Guild(name: "Adventurers", root: true).save(flush: true)
        Guild assassins = new Guild(name: "Assassins", root: true).save(flush: true)
        Guild priests = new Guild(name: "Priests", root: true).save(flush: true)
        Guild thieves = new Guild(name: "Thieves", root: true).save(flush: true)
        Guild warriors = new Guild(name: "Warriors", root: true).save(flush: true)
        Guild wizards = new Guild(name: "Wizards", root: true).save(flush: true)
        
        Guild witches = new Guild(name: "Witches", root: true).save(flush: true)
        witches.addToPrimaries(maspof)
        witches.addToPrimaries(maspde)
        witches.addToPrimaries(maspmi)
        witches.addToPrimaries(maspsp)
        witches.addToPrimaries(mamemechan)
        witches.addToPrimaries(mamemechar)
        witches.addToPrimaries(mamemecu)
        witches.addToPrimaries(mamephbr)
        witches.addToPrimaries(mamephch)
        witches.addToPrimaries(mamephda)
        witches.addToPrimaries(maithebr)
        witches.addToPrimaries(maitwoam)
        witches.addToPrimaries(maitwori)
        witches.addToPrimaries(maitta)
        witches.addToPrimaries(mapo)
        
        Guild cs = new Guild(name: "Conlegium Sicariorum", root: false, parent: assassins).save(flush: true)
        cs.addToPrimaries(fidedo)
        cs.addToPrimaries(fimeda)
        cs.addToPrimaries(firath)
        cs.addToPrimaries(firafi)
        cs.addToPrimaries(admoclroc)
        cs.addToPrimaries(admoclrop)
        cs.addToPrimaries(costin)
        cs.addToPrimaries(costou)
        cs.addToPrimaries(cohipe)
        cs.addToPrimaries(colodo)
        cs.addToPrimaries(colotr)
        cs.addToPrimaries(coitpo)
        cs.addToPrimaries(coittr)
        cs.addToPrimaries(coitwe)
        cs.addToPrimaries(copo)
        
        Guild hash = new Guild(name: "Hashishim", root: false, parent: assassins).save(flush: true)
        hash.addToPrimaries(fidedo)
        hash.addToPrimaries(fimeda)
        hash.addToPrimaries(fimesw)
        hash.addToPrimaries(firath)
        hash.addToPrimaries(admorica)
        hash.addToPrimaries(admoclrop)
        hash.addToPrimaries(admoclroc)
        hash.addToPrimaries(costin)
        hash.addToPrimaries(costou)
        hash.addToPrimaries(cohipe)
        hash.addToPrimaries(cohiob)
        hash.addToPrimaries(colodo)
        hash.addToPrimaries(cocape)
        hash.addToPrimaries(coitwe)
        hash.addToPrimaries(copo)
        
        Guild mr = new Guild(name: "Mano Rossa", root: false, parent: assassins).save(flush: true)
        mr.addToPrimaries(fidedo)
        mr.addToPrimaries(fimeda)
        mr.addToPrimaries(fiungr)
        mr.addToPrimaries(firath)
        mr.addToPrimaries(admoclroc)
        mr.addToPrimaries(admocltr)
        mr.addToPrimaries(costin)
        mr.addToPrimaries(costou)
        mr.addToPrimaries(cohipe)
        mr.addToPrimaries(colodo)
        mr.addToPrimaries(colotr)
        mr.addToPrimaries(coittr)
        mr.addToPrimaries(cocape)
        mr.addToPrimaries(coitwe)
        mr.addToPrimaries(copo)
        
        Guild ninja = new Guild(name: "Ninja", root: false, parent: assassins).save(flush: true)
        ninja.addToPrimaries(fidedo)
        ninja.addToPrimaries(fimesw)
        ninja.addToPrimaries(firafi)
        ninja.addToPrimaries(fiunst)
        ninja.addToPrimaries(admocorop)
        ninja.addToPrimaries(pecuag)
        ninja.addToPrimaries(costin)
        ninja.addToPrimaries(costou)
        ninja.addToPrimaries(cohipe)
        ninja.addToPrimaries(colodo)
        ninja.addToPrimaries(colotr)
        ninja.addToPrimaries(comasl)
        ninja.addToPrimaries(coitpo)
        ninja.addToPrimaries(coitwe)
        ninja.addToPrimaries(copo)
        
        Guild fish = new Guild(name: "Fish", root: false, parent: priests).save(flush: true)
        fish.addToPrimaries(fariofar)
        fish.addToPrimaries(fariofta)
        fish.addToPrimaries(faridear)
        fish.addToPrimaries(faridese)
        fish.addToPrimaries(farideta)
        fish.addToPrimaries(faricuse)
        fish.addToPrimaries(faricuta)
        fish.addToPrimaries(farimiar)
        fish.addToPrimaries(farimise)
        fish.addToPrimaries(farimita)
        fish.addToPrimaries(farisp)
        fish.addToPrimaries(faitro)
        fish.addToPrimaries(faitsc)
        fish.addToPrimaries(fapo)
        
        Guild gapp = new Guild(name: "Gapp", root: false, parent: priests).save(flush: true)
        gapp.addToPrimaries(fariofar)
        gapp.addToPrimaries(fariofta)
        gapp.addToPrimaries(faridear)
        gapp.addToPrimaries(faridese)
        gapp.addToPrimaries(farideta)
        gapp.addToPrimaries(faricuse)
        gapp.addToPrimaries(faricuta)
        gapp.addToPrimaries(farimiar)
        gapp.addToPrimaries(farimise)
        gapp.addToPrimaries(farimita)
        gapp.addToPrimaries(farisp)
        gapp.addToPrimaries(faitro)
        gapp.addToPrimaries(faitsc)
        gapp.addToPrimaries(fapo)
        
        Guild gufnork = new Guild(name: "Gufnork", root: false, parent: priests).save(flush: true)
        gufnork.addToPrimaries(fariofar)
        gufnork.addToPrimaries(fariofta)
        gufnork.addToPrimaries(faridear)
        gufnork.addToPrimaries(faridese)
        gufnork.addToPrimaries(farideta)
        gufnork.addToPrimaries(faricuse)
        gufnork.addToPrimaries(faricuta)
        gufnork.addToPrimaries(farimiar)
        gufnork.addToPrimaries(farimise)
        gufnork.addToPrimaries(farimita)
        gufnork.addToPrimaries(farisp)
        gufnork.addToPrimaries(faitro)
        gufnork.addToPrimaries(faitsc)
        gufnork.addToPrimaries(fapo)
        
        Guild hat = new Guild(name: "Hat", root: false, parent: priests).save(flush: true)
        hat.addToPrimaries(fariofar)
        hat.addToPrimaries(fariofta)
        hat.addToPrimaries(faridear)
        hat.addToPrimaries(faridese)
        hat.addToPrimaries(farideta)
        hat.addToPrimaries(faricuse)
        hat.addToPrimaries(faricuta)
        hat.addToPrimaries(farimiar)
        hat.addToPrimaries(farimise)
        hat.addToPrimaries(farimita)
        hat.addToPrimaries(farisp)
        hat.addToPrimaries(faitro)
        hat.addToPrimaries(faitsc)
        hat.addToPrimaries(fapo)
        
        Guild pishe = new Guild(name: "Pishe", root: false, parent: priests).save(flush: true)
        pishe.addToPrimaries(fariofar)
        pishe.addToPrimaries(fariofta)
        pishe.addToPrimaries(faridear)
        pishe.addToPrimaries(faridese)
        pishe.addToPrimaries(farideta)
        pishe.addToPrimaries(faricuse)
        pishe.addToPrimaries(faricuta)
        pishe.addToPrimaries(farimiar)
        pishe.addToPrimaries(farimise)
        pishe.addToPrimaries(farimita)
        pishe.addToPrimaries(farisp)
        pishe.addToPrimaries(faitro)
        pishe.addToPrimaries(faitsc)
        pishe.addToPrimaries(fapo)
        
        Guild sandelfon = new Guild(name: "Sandelfon", root: false, parent: priests).save(flush: true)
        sandelfon.addToPrimaries(fariofar)
        sandelfon.addToPrimaries(fariofta)
        sandelfon.addToPrimaries(faridear)
        sandelfon.addToPrimaries(faridese)
        sandelfon.addToPrimaries(farideta)
        sandelfon.addToPrimaries(faricuse)
        sandelfon.addToPrimaries(faricuta)
        sandelfon.addToPrimaries(farimiar)
        sandelfon.addToPrimaries(farimise)
        sandelfon.addToPrimaries(farimita)
        sandelfon.addToPrimaries(farisp)
        sandelfon.addToPrimaries(faitro)
        sandelfon.addToPrimaries(faitsc)
        sandelfon.addToPrimaries(fapo)
        
        Guild sek = new Guild(name: "Sek", root: false, parent: priests).save(flush: true)
        sek.addToPrimaries(fariofar)
        sek.addToPrimaries(fariofta)
        sek.addToPrimaries(faridear)
        sek.addToPrimaries(faridese)
        sek.addToPrimaries(farideta)
        sek.addToPrimaries(faricuse)
        sek.addToPrimaries(faricuta)
        sek.addToPrimaries(farimiar)
        sek.addToPrimaries(farimise)
        sek.addToPrimaries(farimita)
        sek.addToPrimaries(farisp)
        sek.addToPrimaries(faitro)
        sek.addToPrimaries(faitsc)
        sek.addToPrimaries(fapo)
        
        new Guild(name: "Cutpurse", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Mugger", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Prowler", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Safecracker", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Smuggler", root: false, parent: thieves).save(flush: true)
        
        new Guild(name: "Ankh-Morpork Palace Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Djelian Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Hublandish Barbarians", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Hunters", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Imperial Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Klatchian Foreign Legion", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Lancre Highland Regiment", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Musketeers", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Samurai", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Weapon Masters Court", root: false, parent: warriors).save(flush: true)
        
        new Guild(name: "Circle", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Hoodwinkers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Last Order", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Lodgers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Midnight", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Seers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Shadows", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Silver Stars", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Klatch", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Students", root: false, parent: wizards).save(flush: true)
        new Guild(name: "White", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Blue", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Octarine", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Red", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Grey", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Green", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Black", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Brown", root: false, parent: wizards).save(flush: true)
    }
    
    private void createGuilds() {
        log.info("Bootstrapping guilds.")
        
        Guild adventurers = new Guild(name: "Adventurers", root: true).save(flush: true)
        Guild assassins = new Guild(name: "Assassins", root: true).save(flush: true)
        Guild priests = new Guild(name: "Priests", root: true).save(flush: true)
        Guild thieves = new Guild(name: "Thieves", root: true).save(flush: true)
        Guild warriors = new Guild(name: "Warriors", root: true).save(flush: true)
        Guild witches = new Guild(name: "Witches", root: true).save(flush: true)
        Guild wizards = new Guild(name: "Wizards", root: true).save(flush: true)
        
        Guild cs = new Guild(name: "Conlegium Sicariorum", root: false, parent: assassins).save(flush: true)
        cs.addToPrimaries(fidedo, )
        
        Guild hash = new Guild(name: "Hashishim", root: false, parent: assassins).save(flush: true)
        Guild mr = new Guild(name: "Mano Rossa", root: false, parent: assassins).save(flush: true)
        Guild ninja = new Guild(name: "Ninja", root: false, parent: assassins).save(flush: true)
        
        new Guild(name: "Fish", root: false, parent: priests).save(flush: true)
        new Guild(name: "Gapp", root: false, parent: priests).save(flush: true)
        new Guild(name: "Gufnork", root: false, parent: priests).save(flush: true)
        new Guild(name: "Hat", root: false, parent: priests).save(flush: true)
        new Guild(name: "Pishe", root: false, parent: priests).save(flush: true)
        new Guild(name: "Sandelfon", root: false, parent: priests).save(flush: true)
        new Guild(name: "Sek", root: false, parent: priests).save(flush: true)
        
        new Guild(name: "Cutpurse", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Mugger", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Prowler", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Safecracker", root: false, parent: thieves).save(flush: true)
        new Guild(name: "Smuggler", root: false, parent: thieves).save(flush: true)
        
        new Guild(name: "Ankh-Morpork Palace Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Djelian Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Hublandish Barbarians", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Hunters", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Imperial Guard", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Klatchian Foreign Legion", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Lancre Highland Regiment", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Musketeers", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Samurai", root: false, parent: warriors).save(flush: true)
        new Guild(name: "Weapon Masters Court", root: false, parent: warriors).save(flush: true)
        
        new Guild(name: "Circle", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Hoodwinkers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Last Order", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Lodgers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Midnight", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Seers", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Shadows", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Silver Stars", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Klatch", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Students", root: false, parent: wizards).save(flush: true)
        new Guild(name: "White", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Blue", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Octarine", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Red", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Grey", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Green", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Black", root: false, parent: wizards).save(flush: true)
        new Guild(name: "Brown", root: false, parent: wizards).save(flush: true)
    }
	
    def destroy = {
        
    }
}